# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aauship/LLIinput.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LLIinput(genpy.Message):
  _md5sum = "a94107953bed535b2b14516497d99ca7"
  _type = "aauship/LLIinput"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# This is the lli input message format for AAUSHIP
uint8 DevID
uint8 MsgID
int16 Data
float64 Time
"""
  __slots__ = ['DevID','MsgID','Data','Time']
  _slot_types = ['uint8','uint8','int16','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       DevID,MsgID,Data,Time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LLIinput, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.DevID is None:
        self.DevID = 0
      if self.MsgID is None:
        self.MsgID = 0
      if self.Data is None:
        self.Data = 0
      if self.Time is None:
        self.Time = 0.
    else:
      self.DevID = 0
      self.MsgID = 0
      self.Data = 0
      self.Time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2Bhd.pack(_x.DevID, _x.MsgID, _x.Data, _x.Time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.DevID, _x.MsgID, _x.Data, _x.Time,) = _struct_2Bhd.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2Bhd.pack(_x.DevID, _x.MsgID, _x.Data, _x.Time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.DevID, _x.MsgID, _x.Data, _x.Time,) = _struct_2Bhd.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2Bhd = struct.Struct("<2Bhd")
