# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aauship/testSetpoints.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class testSetpoints(genpy.Message):
  _md5sum = "7ae8885587dd6aa4814f0117556b4b24"
  _type = "aauship/testSetpoints"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Thi is the msg format for the control-test-node and rqt_mypkg
# interface
float64 cmd_vel
float64 cmd_angvel
float64 cmd_ang
int64 controller_type
"""
  __slots__ = ['cmd_vel','cmd_angvel','cmd_ang','controller_type']
  _slot_types = ['float64','float64','float64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cmd_vel,cmd_angvel,cmd_ang,controller_type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(testSetpoints, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.cmd_vel is None:
        self.cmd_vel = 0.
      if self.cmd_angvel is None:
        self.cmd_angvel = 0.
      if self.cmd_ang is None:
        self.cmd_ang = 0.
      if self.controller_type is None:
        self.controller_type = 0
    else:
      self.cmd_vel = 0.
      self.cmd_angvel = 0.
      self.cmd_ang = 0.
      self.controller_type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3dq.pack(_x.cmd_vel, _x.cmd_angvel, _x.cmd_ang, _x.controller_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.cmd_vel, _x.cmd_angvel, _x.cmd_ang, _x.controller_type,) = _struct_3dq.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3dq.pack(_x.cmd_vel, _x.cmd_angvel, _x.cmd_ang, _x.controller_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.cmd_vel, _x.cmd_angvel, _x.cmd_ang, _x.controller_type,) = _struct_3dq.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3dq = struct.Struct("<3dq")
