// Generated by gencpp from file aauship/Faps.msg
// DO NOT EDIT!


#ifndef AAUSHIP_MESSAGE_FAPS_H
#define AAUSHIP_MESSAGE_FAPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aauship
{
template <class ContainerAllocator>
struct Faps_
{
  typedef Faps_<ContainerAllocator> Type;

  Faps_()
    : DevID()
    , MsgID()
    , Data()
    , Time(0.0)  {
    }
  Faps_(const ContainerAllocator& _alloc)
    : DevID(_alloc)
    , MsgID(_alloc)
    , Data(_alloc)
    , Time(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _DevID_type;
  _DevID_type DevID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _MsgID_type;
  _MsgID_type MsgID;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _Data_type;
  _Data_type Data;

   typedef double _Time_type;
  _Time_type Time;




  typedef boost::shared_ptr< ::aauship::Faps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aauship::Faps_<ContainerAllocator> const> ConstPtr;

}; // struct Faps_

typedef ::aauship::Faps_<std::allocator<void> > Faps;

typedef boost::shared_ptr< ::aauship::Faps > FapsPtr;
typedef boost::shared_ptr< ::aauship::Faps const> FapsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aauship::Faps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aauship::Faps_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aauship

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'aauship': ['/home/aauship/p8-vessel-main/ROS/code/hli/ros/src/aauship/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aauship::Faps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aauship::Faps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aauship::Faps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aauship::Faps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aauship::Faps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aauship::Faps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aauship::Faps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f77a3297cbfe51015202ca7cbc1fc789";
  }

  static const char* value(const ::aauship::Faps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf77a3297cbfe5101ULL;
  static const uint64_t static_value2 = 0x5202ca7cbc1fc789ULL;
};

template<class ContainerAllocator>
struct DataType< ::aauship::Faps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aauship/Faps";
  }

  static const char* value(const ::aauship::Faps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aauship::Faps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is the message format for AAUSHIP called faps\n\
string DevID\n\
string MsgID\n\
string[] Data\n\
float64 Time\n\
";
  }

  static const char* value(const ::aauship::Faps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aauship::Faps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.DevID);
      stream.next(m.MsgID);
      stream.next(m.Data);
      stream.next(m.Time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Faps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aauship::Faps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aauship::Faps_<ContainerAllocator>& v)
  {
    s << indent << "DevID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.DevID);
    s << indent << "MsgID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.MsgID);
    s << indent << "Data[]" << std::endl;
    for (size_t i = 0; i < v.Data.size(); ++i)
    {
      s << indent << "  Data[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Data[i]);
    }
    s << indent << "Time: ";
    Printer<double>::stream(s, indent + "  ", v.Time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AAUSHIP_MESSAGE_FAPS_H
