// Generated by gencpp from file aauship/KFStates.msg
// DO NOT EDIT!


#ifndef AAUSHIP_MESSAGE_KFSTATES_H
#define AAUSHIP_MESSAGE_KFSTATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace aauship
{
template <class ContainerAllocator>
struct KFStates_
{
  typedef KFStates_<ContainerAllocator> Type;

  KFStates_()
    : header()
    , x(0.0)
    , y(0.0)
    , phi(0.0)
    , theta(0.0)
    , psi(0.0)
    , u(0.0)
    , v(0.0)
    , p(0.0)
    , q(0.0)
    , r(0.0)  {
    }
  KFStates_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , phi(0.0)
    , theta(0.0)
    , psi(0.0)
    , u(0.0)
    , v(0.0)
    , p(0.0)
    , q(0.0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _phi_type;
  _phi_type phi;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _psi_type;
  _psi_type psi;

   typedef float _u_type;
  _u_type u;

   typedef float _v_type;
  _v_type v;

   typedef float _p_type;
  _p_type p;

   typedef float _q_type;
  _q_type q;

   typedef float _r_type;
  _r_type r;




  typedef boost::shared_ptr< ::aauship::KFStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aauship::KFStates_<ContainerAllocator> const> ConstPtr;

}; // struct KFStates_

typedef ::aauship::KFStates_<std::allocator<void> > KFStates;

typedef boost::shared_ptr< ::aauship::KFStates > KFStatesPtr;
typedef boost::shared_ptr< ::aauship::KFStates const> KFStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aauship::KFStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aauship::KFStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aauship

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'aauship': ['/home/aauship/p8-vessel-main/ROS/code/hli/ros/src/aauship/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aauship::KFStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aauship::KFStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aauship::KFStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aauship::KFStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aauship::KFStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aauship::KFStates_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aauship::KFStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52d60a9c9b010dccd3a9504f37e35674";
  }

  static const char* value(const ::aauship::KFStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52d60a9c9b010dccULL;
  static const uint64_t static_value2 = 0xd3a9504f37e35674ULL;
};

template<class ContainerAllocator>
struct DataType< ::aauship::KFStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aauship/KFStates";
  }

  static const char* value(const ::aauship::KFStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aauship::KFStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Kalman filter satates\n\
Header header\n\
float32 x \n\
float32 y \n\
float32 phi \n\
float32 theta \n\
float32 psi \n\
float32 u \n\
float32 v \n\
float32 p \n\
float32 q \n\
float32 r\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::aauship::KFStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aauship::KFStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.phi);
      stream.next(m.theta);
      stream.next(m.psi);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.p);
      stream.next(m.q);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KFStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aauship::KFStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aauship::KFStates_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "phi: ";
    Printer<float>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "psi: ";
    Printer<float>::stream(s, indent + "  ", v.psi);
    s << indent << "u: ";
    Printer<float>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "q: ";
    Printer<float>::stream(s, indent + "  ", v.q);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AAUSHIP_MESSAGE_KFSTATES_H
