// Generated by gencpp from file aauship/testSetpoints.msg
// DO NOT EDIT!


#ifndef AAUSHIP_MESSAGE_TESTSETPOINTS_H
#define AAUSHIP_MESSAGE_TESTSETPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aauship
{
template <class ContainerAllocator>
struct testSetpoints_
{
  typedef testSetpoints_<ContainerAllocator> Type;

  testSetpoints_()
    : cmd_vel(0.0)
    , cmd_angvel(0.0)
    , cmd_ang(0.0)
    , controller_type(0)  {
    }
  testSetpoints_(const ContainerAllocator& _alloc)
    : cmd_vel(0.0)
    , cmd_angvel(0.0)
    , cmd_ang(0.0)
    , controller_type(0)  {
  (void)_alloc;
    }



   typedef double _cmd_vel_type;
  _cmd_vel_type cmd_vel;

   typedef double _cmd_angvel_type;
  _cmd_angvel_type cmd_angvel;

   typedef double _cmd_ang_type;
  _cmd_ang_type cmd_ang;

   typedef int64_t _controller_type_type;
  _controller_type_type controller_type;




  typedef boost::shared_ptr< ::aauship::testSetpoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aauship::testSetpoints_<ContainerAllocator> const> ConstPtr;

}; // struct testSetpoints_

typedef ::aauship::testSetpoints_<std::allocator<void> > testSetpoints;

typedef boost::shared_ptr< ::aauship::testSetpoints > testSetpointsPtr;
typedef boost::shared_ptr< ::aauship::testSetpoints const> testSetpointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aauship::testSetpoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aauship::testSetpoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aauship

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'aauship': ['/home/aauship/p8-vessel-main/ROS/code/hli/ros/src/aauship/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aauship::testSetpoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aauship::testSetpoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aauship::testSetpoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aauship::testSetpoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aauship::testSetpoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aauship::testSetpoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aauship::testSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ae8885587dd6aa4814f0117556b4b24";
  }

  static const char* value(const ::aauship::testSetpoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ae8885587dd6aa4ULL;
  static const uint64_t static_value2 = 0x814f0117556b4b24ULL;
};

template<class ContainerAllocator>
struct DataType< ::aauship::testSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aauship/testSetpoints";
  }

  static const char* value(const ::aauship::testSetpoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aauship::testSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Thi is the msg format for the control-test-node and rqt_mypkg\n\
# interface\n\
float64 cmd_vel\n\
float64 cmd_angvel\n\
float64 cmd_ang\n\
int64 controller_type\n\
";
  }

  static const char* value(const ::aauship::testSetpoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aauship::testSetpoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_vel);
      stream.next(m.cmd_angvel);
      stream.next(m.cmd_ang);
      stream.next(m.controller_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testSetpoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aauship::testSetpoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aauship::testSetpoints_<ContainerAllocator>& v)
  {
    s << indent << "cmd_vel: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_vel);
    s << indent << "cmd_angvel: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_angvel);
    s << indent << "cmd_ang: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_ang);
    s << indent << "controller_type: ";
    Printer<int64_t>::stream(s, indent + "  ", v.controller_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AAUSHIP_MESSAGE_TESTSETPOINTS_H
